### PR TITLE
[BUG] devs can't use db!forceleave 

### LINKED ISSUE #77: [BUG] Devs can't use forceleave

### PR DESCRIPTION
**Pull request by duncte123**
Fixes #77

- [x] I have tested my changes.
- [ ] I didn't test my changes. I will do that in the following 7 days and agree that this Pull request will be closed if I don't test it in the named time span.
- [x] I know the language good enough for providing high-quality code.

Changes proposed in this pull request:
---

- Updated kotlin, coroutines and JDA-Utils

- Fixed the forceleave command, devs can now use it everywhere

### CODE REVIEW

File: src/main/kotlin/ml/duncte123/skybot/Annotations.kt [hunk 1]
```diff
@@ -61,7 +61,8 @@ annotation class DocumentationNeeded(vararg val specificPart: String = ["everyth
 @Retention(SOURCE)
 @SinceSkybot("3.51.10")
 @Author(nickname = "Sanduhr32", author = "Maurice R S")
-annotation class Author(val author: String = "Duncan Sterken", val nickname: String = "duncte123")
+//annotation class Author(val author: String = "Duncan Sterken", val nickname: String = "duncte123")
+annotation class Author(val author: String, val nickname: String)
```
Comment (ramidzkh) [inline src/main/kotlin/ml/duncte123/skybot/Annotations.kt]: Thank god, IntelliJ warns me everywhere about this

Comment (duncte123) [reply src/main/kotlin/ml/duncte123/skybot/Annotations.kt]: You're welcome
